# Generated by Django 2.1.4 on 2018-12-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('ELECTRICIAN', 'Electrician'), ('PLUMBING', 'Plumbing'), ('CLEANING', 'Cleaning'), ('PEST', 'Pest & Termite'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('ROOFING', 'Roofing'), ('HVAC', 'HVAC'), ('HANDYMAN', 'Handyman')], default='HANDYMAN', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('password', models.CharField(default='password', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='main.Property'),
        ),
    ]
