# Generated by Django 2.1.4 on 2018-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subcategory',
            field=models.CharField(choices=[('REPLACE ELECTRICAL BOX', 'Replace Electrical Box'), ('REPLACE SWITCHES', 'Replace Switches'), ('WIRING', 'Wiring'), ('REPLACE FIXTURES', 'Replace Fixtures'), ('CLOGGED DRAIN', 'Clogged Drain'), ('NEW TAP', 'New Tap'), ('CRACKED PIPE', 'Cracked Pipe'), ('SLOW OR CLOGGED DRAIN', 'Slow or Clogged Drain'), ('PIPE BLOCKED', 'Pipe Blocked'), ('CLOGGED TOILET', 'Clogged Toilet'), ('PIPE BROKEN', 'Pipe Broken'), ('AIR LOCKED', 'Air Locked'), ('LEAKY HOSE BIB', 'Leaky Hose Bib'), ('WATER HEATER', 'Water Heater'), ('SUMP PUMP FAILURE', 'Sump Pump Failure'), ('LOW WATER PRESSURE', 'Low Water Pressure'), ('DRIPPING FAUCET', 'Dripping Faucet'), ('ROUTINE HOME CLEANING', 'Routine Home Cleaning'), ('HOME CLEAN PRE/POST MOVE', 'Home Clean Pre/Post Move'), ('HOME DEEP CLEAN', 'Home Deep Clean'), ('ANTS', 'Ants'), ('TERMITE LETTER', 'Termite Letter'), ('TERMITE CONTROL', 'Termite Control'), ('MOSQUITO CONTROL', 'Mosquito Control'), ('VERMIN/LARGE PESTS', 'Vermin/Large Pests'), ('TOUCH UP', 'Touch Up'), ('TRIM', 'Trim'), ('LIGHT SHEETROCK/MUD', 'Light Sheetrock/Mud'), ('SHEETROCK', 'Sheetrock'), ('WINDOWS', 'Windows'), ('DOORS', 'Doors'), ('CABINETS AND SHELVING', 'Cabinets and Shelving'), ('WATER DAMAGE REMEDIATION', 'Water Damage Remediation'), ('MOLD REMEDIATION', 'Mold Remediation'), ('BIOHAZARD/ANIMAL WASTE REMOVAL', 'BioHazard/Animal Waste Removal'), ('RADON TESTING', 'Radon Testing'), ('ROOF REPLACEMENT', 'Roof Replacement'), ('GUTTERS', 'Gutters'), ('ROOF REPAIRS', 'Roof Repairs'), ('BLOCKED VENTS', 'Blocked Vents'), ('FAULTY THERMOSTAT', 'Faulty Thermostat'), ('AC NOT COOLING', 'AC Not Cooling'), ('PRESSURE IMBALANCE', 'Pressure Imbalance'), ('COMPRESSOR FAILURE', 'Compressor Failure'), ('INSULATION', 'Insulation'), ('HARDWOOD INSTALL AND REPAIR', 'Hardwood Install and Repair'), ('CARPET INSTALL AND REPAIR', 'Carpet Install and Repair'), ('TILE INSTALL AND REPAIR', 'Tile Install and Repair'), ('OTHER', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='profession',
            field=models.CharField(choices=[('ELECTRICIAN', 'Electrician'), ('PLUMBING', 'Plumbing'), ('CLEANING', 'Cleaning'), ('PEST', 'Pest & Termite'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('MOLD AND BIOHAZARD', 'Mold and BioHazard'), ('ROOFING', 'Roofing'), ('HVAC', 'HVAC'), ('HANDYMAN', 'Handyman')], default='Handyman', max_length=255),
        ),
    ]
