# Generated by Django 2.1.4 on 2018-12-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181212_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='properties',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='users',
            new_name='user',
        ),
    ]
