# Generated by Django 2.1.4 on 2018-12-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholderName', models.CharField(max_length=255)),
                ('cardType', models.CharField(choices=[('AMEX', 'Amex'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('DISCOVER', 'Discover')], default='Visa', max_length=255)),
                ('cardNumber', models.CharField(max_length=16)),
                ('cardCVV', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.User')),
            ],
        ),
    ]
