# Generated by Django 2.1.4 on 2018-12-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='time',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='timeslot',
            field=models.CharField(default='11pm-1pm', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardMonth',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardYear',
            field=models.CharField(default='30', max_length=2),
        ),
    ]
