import React, { Component } from 'react'
import styled from 'styled-components'

const Guarantee = styled.div`
    margin: 4em 0 .4em 3em;
    h2 {
        color: rgba(14,151,255,1);
        font-size: 4em;
    }
    p {
        color: rgba(112,112,112,1);
        font-size: 2.5em;
        margin: 2em auto;
    }
`

class UserTerms extends Component {
    render() {
        return (
            <div>
                <Guarantee>
                    <h2>User Terms</h2>
                    <p>Last Updated: January 12, 2018</p>
                    <p>The Jonny On It mobile application revolutionizes the home services experience. We empower consumers with the ability to secure and effect home repairs almost effortlessly. We use real-time geo-location, satisfaction ratings, and integrated billing to make the home services experience easier and cheaper for customers and more profitable for service providers.</p>
                    <p>The following terms and conditions outline your obligations as a User and the conditions on which We allow You to access and use the Platform.</p>
                    <p>PLEASE READ THESE TERMS CAREFULLY. BY REGISTERING AS A USER OR OTHERWISE ACCESSING, DOWNLOADING, OR USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS AND OUR PRIVACY POLICY. YOU FURTHER AGREE TO BE BOUND BY ALL APPLICABLE LAWS AND REGULATIONS RELATING TO THE PLATFORM. IF YOU DO NOT AGREE WITH ANY OF THESE TERMS, YOU ARE PROHIBITED FROM USING OR ACCESSING THE PLATFORM AND YOUR STATUS AS A “USER” IS HEREBY TERMINATED.</p>
                    <h2>Definitions</h2>
                    <p>As used in these Terms, the following capitalized terms shall have the meanings set forth below:</p>
                    <p>Insert Table Here</p>
                    <h2>Modifications of Terms</h2>
                    <p>We may modify or update the Terms at any time, with or without notice to You. When We do, We will update the “Last Updated” date at the top and the amended Terms shall be effective as of such date. If You do not agree with the amendments, You are no longer authorized as a User and are prohibited from using or accessing the Platform. You must immediately stop using the Platform and notify Us to disable your User account. Your continued access and/or use of the Platform after any such amendment constitutes your acceptance of and agreement to be bound by the amended Terms.</p>
                    <h2>Jobs</h2>
                    <p>The Platform enables You to research, request, and commission the services offered by Providers. By using the Platform, You acknowledge that We do not perform Jobs and the Providers are third-parties over whom We exercise no control. We do not control what or how Jobs are performed for You; We do not provide tools, supplies, or materials to Providers; and We do not reimburse Providers for expenses incurred related to the performance of Jobs. We have no responsibility or liability for the Providers or the Jobs that they perform. Providers on our Platform may change frequently; We have no responsibility to maintain any Provider on the Platform.</p>
                    <p>No joint venture, partnership, employment or agency relationship exists between You or any Provider and Jonny On It as a result of these Terms, use of the Platform, performance of Jobs, or otherwise. None of these parties have any authority to bind the others in any respect.</p>
                    <h2>Payment; Taxes; Disputes</h2>
                    <p>Payment Processing: By using our Platform, You agree that payment for Jobs will be facilitated via the Platform through a third-party payment processor. Our third-party payment processors charge payment processing fees for each transaction completed through the Platform and such fees are included in the fees that You pay to a Provider. The processing of payments will be subject to the terms, conditions, and privacy policies of our payment processors, in addition to this agreement. You hereby authorize Us to take all action necessary with our payment processor, on your behalf, to effect the transactions contemplated by these Terms or any Order.</p>
                    <p>Stripe: Without limiting the generality of the foregoing, Stripe is one of our payment processors. We have contracted with Stripe to utilize its Stripe Connect services. You can learn more about Stripe Connect at https://stripe.com/connect. All payments made via Stripe on the Platform are processed according to Stripe’s terms and conditions and Privacy Policy. You expressly authorize and grant Us the right, power, and authority to (acting on your behalf) access and transmit your data to Stripe as reasonably necessary for Us to facilitate your use of the Platform. We do not control and are not liable for the security or performance of any of our payment processors or other third party service providers. We reserve the right to correct, or instruct one or more of our payment processors to correct, any errors or mistakes, even if payment has already been requested or received.</p>
                    <p>You hereby authorize Us to share with Stripe any and all information related to You, the Jobs, the Platform, your use of the Platform, the data that You input into the Platform, your Orders, the JOI Fees, all other fees associated with Orders and/or Jobs, and all other information and data about your Platform account and transactions with Providers.</p>
                    <p>Payment Collection: You must provide a valid method of payment when You register to be a User. You may change your method of payment at any time by selecting “Payment” in the App. All payments from Users to Providers will be processed through Stripe’s services. We strictly prohibit cash payments, donations, tips, or any exchange of money outside of the Platform between You and any Provider. You agree that You will not make or accept cash payments from Providers under any condition and that all future monetary transactions between You and any Provider will be through the Platform. This includes payments for or associated with any and all future services provided to You by any Provider You became aware of through the Platform and any category of service (plumbing, electricity, HVAC, painting, etc.). Providers determine the amount of fees owed for each Service they provide; We have no control over the fees.</p>
                    <p>When a Provider completes the agreed-upon Jobs for You, the Provider will use the Platform to change the status of the Jobs to “Job Done”. This will trigger payment collection from You of all fees due according to the Provider. If You are unhappy with the Jobs, You can dispute the charge and payment extraction will be cancelled until You and the Provider have resolved the dispute, at which time the Provider will again initiate payment through the Platform. You have thirty (30) minutes from the time Provider changes the status of the Job to “Job Done” to dispute the charge. After thirty (30) minutes, the Jobs are deemed approved and accepted and your payment method will be charged the agreed-upon amount. If You do not timely dispute the Jobs, payment will automatically be collected from Your account. For each transaction, the Provider will receive the fees minus the JOI Fee, as calculated in Appendix A (Jonny On It Fees).</p>
                    <p>User Payment Disputes: If You dispute the Jobs performed by a Provider for any reason within thirty (30) minutes of the status change to “Job Done”, the Provider will be notified and extraction of payment will be cancelled. We expect You to work with the Provider to resolve the dispute. We are not a party to the agreement or Orders between You and any Provider and are not responsible for disputes or misunderstandings arising from the Jobs or the cost, quality, or estimates associated therewith. Upon resolution of the dispute, the Provider will request payment (of the original or a modified amount) from You through the Platform; this request is deemed identical to a status change to “Job Done” and triggers the same 30-minute dispute period and dispute process.</p>
                    <h2>Order Cancellation</h2>
                    <p>You may cancel an Order at any time. If You cancel within five minutes of submitting a request for Jobs, no payment is due. If You cancel more than five minutes after an Order is confirmed, but before the Provider arrives at the location, You must pay a $15 cancellation fee. If You cancel after the Provider arrives to perform the Jobs, You will pay a $30 cancellation fee plus any fees owed to the Provider for the portion of the Jobs performed prior to cancellation.</p>
                    <p>A Provider may cancel an Order at any time prior to completion. We recommend that Providers communicate with You prior to cancellation to avoid disputes over fees due for Jobs completed prior to cancellation</p>
                    <p>If, at any time and in a Provider’s sole discretion, the Provider deems the work location for an Order to be a hazard to persons or property for any reason, including, without limitation, due to the presence of hazardous materials, animals, or environmental hazards, the Provider may cancel the Oder and You will pay all fees owed to the Provider for the portion of the Jobs performed prior to cancellation. If the Provider cancels the Order prior to commencing performance of the Jobs due to an Undisclosed Condition, You will be charged a $45 cancellation fee.</p>
                    <p>If a Provider cancels an Order for any reason, We will notify You and You may make the Jobs request available to other Providers on the Platform. We cannot guarantee that You will find another Provider to perform the Jobs.</p>
                    <p>All payments made on the Platform are non-refundable, except by mutual agreement between You and the Provider.</p>
                    <h2>License</h2>
                    <p>We hereby grant You a limited, non-exclusive, revocable, non-transferable, non-sublicensable, license to use the Platform for the limited purposes of soliciting and entering into Orders with Providers to perform Jobs for You, subject to these Terms. Nothing herein shall transfer any ownership rights in or to the Platform to You.</p>
                    <p>We hereby grant You a limited, non-exclusive, revocable, non-transferable, non-sublicensable, license to use the Platform for the limited purposes of soliciting and entering into Orders with Providers to perform Jobs for You, subject to these Terms. Nothing herein shall transfer any ownership rights in or to the Platform to You.</p>
                    <p>You must not (a) make the Platform available to any third party (including any employee, agent, or associate); (b) allow any third party to access the Platform using your username or password; (c) use the Platform to store or transmit any content that may be infringing, defamatory, threatening, harmful, or otherwise tortious or unlawful, including any content that may violate the intellectual property, privacy, or publicity rights of any third party or other laws; (d) use the Platform to send spam or other unsolicited messages in violation of applicable law; (e) upload to or transmit from the Platform any data, file, software, or link that contains or redirects to a virus, Trojan horse, worm, or other harmful component; (f) attempt to reverse engineer, decompile, hack, disable, interfere with, disassemble, copy, or otherwise disrupt in any way the integrity or performance of the Platform, any third party use of the Platform, or any third party data contained therein; (g) access the Platform in order to build a competitive product or service or to copy any ideas, features, functions, or graphics of the Platform; (h) attempt to use or gain unauthorized access to the Platform, any feature thereof, or its related systems or networks; (i) remove any copyright notice or statement or other notice or statement of proprietary rights associated with the Platform or any feature or component thereof; (j) mirror the Platform on any other server; (k) claim, express, or imply, whether in writing, electronically, or orally, that any statements You make are endorsed or authorized by Us; (l) install the Platform on any device that You do not control; or (m) authorize, permit, or encourage any third party to do any of the above.</p>
                    <p>We may immediately terminate the license granted herein and your status as a User if You violate any of these restrictions.</p>
                    <h2>Disclaimer</h2>
                    <p>SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED TERMS IN CONTRACTS WITH CONSUMERS AND AS A RESULT, THE CONTENT OF THIS SECTION MAY NOT APPLY TO YOU. EXCEPT AS EXPRESSLY PROVIDED HEREIN, TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW, JONNY ON IT EXPRESSLY EXCLUDES AND DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF DESIGN, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUALITY, AND NON-INFRINGEMENT, THAT ITS PLATFORM WILL MEET YOUR REQUIREMENTS OR THE REQUIREMENTS OF ANY THIRD PARTY, OR THAT ITS SERVICES WILL BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE, ACCURATE, COMPLETE, OR ERROR-FREE. IN ADDITION, JONNY ON IT DOES NOT WARRANT ANY CONNECTION TO OR TRANSMISSION FROM THE INTERNET. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM US OR ELSEWHERE WILL CREATE ANY WARRANTY OR CONDITION NOT EXPRESSLY STATED IN THESE TERMS EXCEPT. EXCEPT AS EXPRESSLY PROVIDED HEREIN, THE PLATFORM IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY PROVIDED HEREIN. WE DISCLAIM ALL RESPONSIBILITY OR LIABILITY IN RELATION TO THE CONTENT MADE AVAILABLE THROUGH THE PLATFORM, INCLUDING USER- OR PROVIDER-UPLOADED CONTENT, FEEDBACK, AND REVIEWS, OR ANY CONTENT OR SERVICES PROVIDED BY THIRD PARTIES. WE DO NOT CONTROL OR VET USER- OR PROVIDER-UPLOADED CONTENT OR ANY FEEDBACK, REVIEWS, OR OTHER CONTENT POSTED ON OR THROUGH THE PLATFORM AND ARE NOT RESPONSIBLE FOR WHAT USERS POST, TRANSMIT, OR SHARE ON OR THROUGH THE PLATFORM. WE ARE NOT RESPONSIBLE OR LIABLE IN ANY MANNER FOR ANY SUPPORTED SERVICES OR THIRD PARTY PLATFORMS ASSOCIATED WITH OR UTILIZED IN CONNECTION WITH SUCH THIRD PARTY SERVICES, INCLUDING THE FAILURE OF ANY SUCH SUPPORTED SERVICES OR THIRD PARTY PLATFORMS. WE EXPRESSLY DENY ANY RESPONSIBILITY FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE PLATFORM OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN. FINALLY, EXCEPT AS EXPRESSLY PROVIDED HEREIN, WE DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES WITH RESPECT TO THE USERS, PROVIDERS, OR THE SERVICES PERFORMED BY SUCH PROVIDERS, INCLUDING, WITHOUT LIMITATION, ANY REPRESENTATION OR WARRANTY RELATING TO A USER’S OR PROVIDER’S CHARACTER, EDUCATION, TRAINING, SKILL, ABILITY, LICENSURE, OR CERTIFICATION.</p>
                    <p>ou are solely responsible and liable for the determination of whether to hire any given Provider to perform Jobs. We encourage You to perform any investigations and research You feel necessary before entering into an Order with a Provider.</p>
                    <h2>Limitations of Liability</h2>
                    <p>EXCEPT AS EXPRESSLY PROVIDED HEREIN, IN NO EVENT, SHALL OUR AGGREGATE LIABILITY FOR ALL CLAIMS OF ANY KIND, INCLUDING ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS, WHETHER BY STATUTE, CONTRACT, TORT, OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED THE FEES WE HAVE RECEIVED FROM YOU DURING THE SIX MONTH PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH THE CAUSE OF ACTION AROSE.</p>
                    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL JONNY ON IT OR OUR DIRECTORS, EMPLOYEES, AGENTS, ASSOCIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, OR DATA OR OTHER INTANGIBLE LOSSES THAT RESULT FROM THE USE OF, OR INABILITY TO USE, THE PLATFORM OR ANY FEATURE OR FUNCTION THEREOF, EVEN IF WE KNEW OR WERE NOTIFIED OF THE POSSIBILITY OF SUCH DAMAGES. UNDER NO CIRCUMSTANCES WILL WE BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM (A) HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE PLATFORM OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN OR (B) THE ORDER, PERFORMANCE OF SERVICES BY A PROVIDER, OR YOUR RELATIONSHIP WITH A PROVIDER.</p>
                    <p>THE PARTIES ACKNOWLEDGE AND AGREE THAT THE ESSENTIAL PURPOSE OF THIS SECTION IS TO ALLOCATE THE RISKS UNDER THESE TERMS BETWEEN THE PARTIES AND LIMIT THEIR POTENTIAL LIABILITY GIVEN THE FEE STRUCTURE SET FORTH IN THESE TERMS, WHICH WOULD HAVE BEEN SUBSTANTIALLY DIFFERENT IF WE WERE TO ASSUME ANY FURTHER LIABILITY OTHER THAN AS SET FORTH HEREIN. THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THESE TERMS. NOTHING IN THESE TERMS IS INTENDED TO EXCLUDE OR RESTRICT OR SHALL BE CONSTRUED TO EXCLUDE OR RESTRICT OUR LIABILITY FOR (I) THE DEATH OR PERSONAL INJURY CAUSED BY THE NEGLIGENCE OF US, OUR EMPLOYEES, OR AGENTS; (II) WILLFUL MISCONDUCT OF EITHER PARTY; OR (III) ANY LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY APPLICABLE LAW.</p>
                    <h2>Indemnification</h2>
                    <p>Indemnification by Jonny On It: Subject to your compliance with the Indemnification Procedure below, We shall indemnify, defend, and hold harmless User from and against any and all third party claims that the use of the Platform as permitted hereunder infringes the valid U.S. intellectual property or trade secret rights of any third party (a “User Claim”). We shall have no liability for any User Claim to the extent it arises from (i) a modification of the Platform by or at the direction of You or any third party other than Us; (ii) use of the Platform in violation of these Terms or any applicable law; (iii) use of the Platform after We notified You to discontinue use because of an infringement or misappropriation claim; (iv) the combination, operation, or use of the Platform with any other software, program, or device not provided or specified by Us to the extent such infringement would not have arisen but for such combination, operation, or use; or (v) any use of the Platform in a manner that is either inconsistent with its intended use or in breach of these Terms. For avoidance of doubt, our indemnification obligations in this section will not apply to third-party content, User-uploaded content, Provider-uploaded content, or any third party software or hardware accessed through the Platform and/or User or Provider content. If the Platform has become, or in our opinion is likely to become, the subject of any such User Claim, We may, at our sole discretion, option, and expense (a) procure for You the right to continue using the Platform as set forth herein; (b) replace or modify the Platform or certain features or functionalities to make it non-infringing; or (c) if options (a) or (b) are not reasonably practicable, terminate our relationship and these Terms. This section sets forth our sole liability (and your sole remedy) regarding infringement or misappropriation of third party rights.</p>
                    <p>Indemnification by User: You shall indemnify, defend, and hold harmless Jonny On It and our directors, officers, employees, agents, and associates from and against all claims, losses, damages, penalties, liability, and costs, including reasonable attorneys’ fees, of any kind or nature which are in connection with or arising out of a claim (a) alleging that User content infringes or violates the intellectual property, privacy, publicity, trade secret, or other rights of a third party or violates applicable law; (b) alleging that User’s use of the Platform as described in subsections (i) through (v) in the paragraph above infringes or violates the intellectual property, privacy, publicity, trade secret, or other rights of a third party or violates applicable law; (c) relating to or arising from User content; or (d) relating to or arising from any breach of these Terms by User.</p>
                    <p>Indemnification Procedure: The indemnified party shall (a) promptly give written notice of the claim to the indemnifying party; (b) give the indemnifying party sole control of the defense and settlement of the claim (provided that the indemnifying party may not settle or defend any claim without the indemnified party’s prior written consent unless it requires no payment or admission by and unconditionally releases the indemnified party of all liability); and (c) provide the indemnifying party with reasonable cooperation and assistance at the indemnifying party’s expense.</p>
                    <h2>User Representations</h2>
                    <p>You represent and warrant that (i) all information that You provide to Us prior to and while You are a User is true and accurate, to the best of your knowledge; (ii) if You learn or suspect that any information You provided to Us is no longer true and accurate, You will immediately notify Us to correct the information; (iii) You have all necessary right, power, and authority to enter into these Terms with Us and to perform as anticipated by these Terms; (iv) your use of the Platform will not violate any laws or regulations in the U.S. or otherwise; and (v) entering into these Terms with Us or any Order with a Provider and/or using the Platform does not and will not violate any agreement You have with or obligation You owe to any third party.</p>
                    <h2>Intellectual Property</h2>
                    <p>JONNY ON IT and other graphics, logos, designs, page headers, button icons, scripts, and other names are the trademarks or trade dress of Jonny On It. These trademarks and/or trade dress may not be used, including as part of any trademark, service mark, domain name, social media account name, keyword advertisement, email address, or in connection with any product or service in a manner that is likely to cause confusion.</p>
                    <p>You should assume that all content and material made available on the Platform is protected by copyright law. Aside from User- and Provider-uploaded content, all materials and other information on the Platform, including, but not limited to, all text, graphics, logos, icons, images, photos, videos, audio clips, data compilations, and software are the exclusive property of Jonny On It or our licensors and are protected by U.S. and international copyright laws and may not be used without the express written permission of the owner thereof.</p>
                    <h2>You should assume that all content and material made available on the Platform is protected by copyright law. Aside from User- and Provider-uploaded content, all materials and other information on the Platform, including, but not limited to, all text, graphics, logos, icons, images, photos, videos, audio clips, data compilations, and software are the exclusive property of Jonny On It or our licensors and are protected by U.S. and international copyright laws and may not be used without the express written permission of the owner thereof.</h2>
                    <p>Confidential Information: Each party will use the same degree of care that it uses to protect the confidentiality of its own confidential information of like kind (but in no event less than reasonable care) and will not disclose or use any Confidential Information (as defined below) of the other party for any purpose outside of the scope of these Terms, and each party shall limit access to Confidential Information to those of its employees, contractors, and agents who need such access for purposes consistent with these Terms and who have signed confidentiality agreements with the receiving party containing protections no less stringent than those herein. In this Agreement, “Confidential Information” means all information, data, and financial information relating to the business, commercial strategies, pricing, personnel, customers, products, or services of a party not generally known to the public or that by its nature one would generally assume to be confidential (the “discloser”) but excludes any information that the other party (the “recipient”) proves (i) was lawfully in the recipient’s possession before receiving it from the discloser; (ii) is provided in good faith to the recipient by a third party without breaching any rights of the discloser or any other party; (iii) is or becomes generally available to, or accessible by, the public through no fault of the recipient; or (iv) was or is independently developed by the recipient without reference to the discloser’s Confidential Information. In the event that the recipient or any representative of the recipient becomes legally compelled (by law, rule, regulation, subpoena, or similar court process) to disclose any of the Confidential Information, the recipient will (if permitted to do so) provide the discloser with notice of such circumstances and will limit such disclosure to the required disclosure.</p>
                    <p>Security Requirements: While We take steps to employ appropriate technical and organizational security measures, We cannot guarantee that unauthorized third parties will never be able to defeat those measures. We expressly deny any responsibility for damages, monetary or otherwise, resulting from unauthorized third party access to your account or use, alteration, or disclosure of your content or information. We will promptly notify You in writing as soon as We suspect or become aware of actual third party access to your account or use, alteration, or disclosure of your content or information.</p>
                    <h2>Communication, Text Messages, and Phone Calls</h2>
                    <p>By providing phone numbers and/or email addresses and using the Platform, You authorize Us, to the extent permitted by applicable law, to use this information to contact You via voice calls, emails, text (SMS) messages to your electronic devices, and all other methods of communication associated therewith, whether now existing or created in the future in order to facilitate your use of the Platform. You may incur charges from your communication carrier as a result of these messages. You may opt-out of receiving SMS text messages from Us by replying with the word “STOP” to a text message from Us. You acknowledge that opting out of text (SMS) messages may impact your ability to use the Platform.</p>
                    <h2>General</h2>
                    <p>Assignment: You may not assign or otherwise transfer any of your rights or obligations under these Terms, whether by merger, sale of assets, change of control, operation of law or otherwise, without our prior written consent and any attempted assignment without such consent will be void.</p>
                    <p>We may assign these Terms in their entirety without your consent to any affiliated company or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of our shares or assets, provided that We promptly thereafter notify You of such assignment and allow You to terminate these Terms by giving Us 30 days’ notice in writing within 30 days after receipt of such notice of assignment.</p>
                    <p>Governing Law; Jurisdiction: These Terms and all use of the Platform hereunder are governed by the laws of the State of Georgia without regard to its conflict of law provisions. All disputes under these Terms and/or arising from your use of the Platform will be resolved in the courts located in the County of Fulton, State of Georgia. The parties hereby consent to, and agree not to challenge, the jurisdiction and forum designations in this paragraph.</p>
                    <p>Entire Agreement; Severability; Waiver: These terms and other agreements, rules, and policies incorporated by reference into these Terms or posted on the Platform at any time, including without limitation, the Privacy Policy at www.Jonnyonit.com/privacy constitute the entire understanding between You and Jonny On It. Each provision in these Terms is severable. If any provision herein is or becomes illegal, invalid, or unenforceable in any jurisdiction, the illegality, invalidity, or unenforceability of that provision will not affect the legality, validity, or enforceability of the remaining provisions of these Terms or of that provision in any other jurisdiction. No waiver of any provision of these Terms is binding unless in writing and signed by the parties to these Terms. No failure to or delay in exercising any right or remedy under these Terms shall be deemed a waiver of that right or remedy. No waiver of any breach of any provision herein shall be deemed to be a waiver of any subsequent breach of that or any other provision in the future.</p>
                    <h2>Appendix A Jonny On It Fees</h2>
                    <p>Fees will be calculated via the number of transactions, per below:</p>
                    <p>INSERT TABLE HERE</p>
                    <p>Number of Transactions are determined via calendar year (beginning January 1 and ending December 31), and reset annually.</p>
                </Guarantee>
            </div>
        )
    }
}

export default UserTerms